name: CI pour Appli Python / Checkout

on:
  push:
    branches:
      - 'release'

jobs:
  lint:  
    runs-on : ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.1

      - name : Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name : Lint du code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
  build:  
    runs-on : ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name : Installation de librairies python
        run: pip install -r code-appli-python/vote/requirements.txt

      - name : Creation d'un répertoire pour le bundle
        run: mkdir bundle-lab2

      - name : Creation zip
        run: zip -r bundle.zip bundle-lab2

      - name : Suppression
        run: rm -rf bundle-lab2

      - name: Upload d'artéfacts
        uses: actions/upload-artifact@v4
        with: 
          name: bundle.zip
          path: src/

  publish:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: python-bundle
          path: bundle.zip

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: v1.0.0
          release_name: Release v1